version: 0.2

phases:
  install:
    commands:
      - npm install
  post_build:
    commands:
      - aws s3 cp --recursive public/ $S3_DEST
#      - npm install -g serverless
#      - serverless deploy
